---
- name: Install toolbox packages
  import_tasks: packages.yml

- name: Install Google Cloud SDK
  import_tasks: gcloud.yml

- name: Configure AI tools
  import_tasks: ai.yml

- name: Configure glab
  import_tasks: glab.yml

- name: Setup ajust
  import_tasks: ajust.yml

- name: Install SparkFabrik HTTP Proxy
  import_tasks: http-proxy.yml
