---
- name: Install sway packages
  import_tasks: install_packages.yml

- name: Configure sway
  tags: [wm, sway]
  when: desktop.sway.enable == true
  block:
    - name: Enable swayosd-libinput-backend service
      shell: systemctl enable swayosd-libinput-backend.service

    - name: Configure login launcher due to this issue - https://github.com/swaywm/sway/issues/3109
      ansible.builtin.copy:
        src: sway-shell.desktop
        dest: /usr/share/wayland-sessions/sway-shell.desktop
