---
- name: Install gnome packages
  import_tasks: install_packages.yml

- name: Configure gnome
  tags: [gnome]
  block:
    - name: "Enable gdm"
      shell: systemctl enable gdm
    - name: "Enable NetworkManager"
      shell: systemctl enable NetworkManager
    - name: "Enable power-profiles-daemon"
      shell: systemctl enable power-profiles-daemon

- name: Configure gnome
  import_tasks: dconf.yml

- name: Configure dash-to-dock
  import_tasks: dash-to-dock.yml

- name: Configure just-perfection
  import_tasks: just-perfection.yml

- name: Install toggle-touchpad
  import_tasks: toggle-touchpad.yml

- name: Configure gnome keybindings
  import_tasks: keybindings.yml

- name: Configure multitouch gestures (x11)
  import_tasks: gestures.yml
