---
- name: Load packages variables
  tags: [packages, base]
  ansible.builtin.include_vars:
    file: "{{ ansible_facts['distribution'] }}.yml"
    name: distro_packages

- name: Install base packages
  tags: [packages, base]
  block:
    - name: Network packages
      when: ansible_facts['distribution'] == "Archlinux"
      community.general.pacman:
        name: "{{ distro_packages.base_pkgs_network }}"

    - name: System packages
      when: ansible_facts['distribution'] == "Archlinux"
      community.general.pacman:
        name: "{{ distro_packages.base_pkgs_system }}"

    - name: System packages from AUR
      when: ansible_facts['distribution'] == "Archlinux"
      kewlfft.aur.aur:
        use: paru
        name: "{{ distro_packages.base_pkgs_system_aur }}"
      become: yes
      become_user: aur_builder

    - name: Symlink vim to vi
      command: ln -sf /usr/bin/vim /usr/bin/vi
