---
- name: Load packages variables
  tags: [packages, fonts]
  ansible.builtin.include_vars:
    file: "{{ ansible_facts['distribution'] }}.yml"
    name: distro_packages

- name: Install and configure fonts
  tags: [packages, fonts]
  when: ansible_facts['distribution'] == "Archlinux"
  block:
    - name: Install fonts
      when: ansible_facts['distribution'] == "Archlinux"
      community.general.pacman:
        update_cache: true
        name: "{{ distro_packages.fonts_pkgs }}"

    - name: Install fonts from aur
      when: ansible_facts['distribution'] == "Archlinux"
      kewlfft.aur.aur:
        use: paru
        name: "{{ distro_packages.fonts_pkgs_aur }}"
      become: yes
      become_user: aur_builder

    - name: Enable rgb subpixel configuration
      file:
        src: "/usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf"
        dest: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf"
        state: link

    - name: Enable slight hinting
      file:
        src: "/usr/share/fontconfig/conf.avail/10-hinting-slight.conf"
        dest: "/etc/fonts/conf.d/10-hinting-slight.conf"
        state: link

    - name: Enable lcd filter
      file:
        src: "/usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf"
        dest: "/etc/fonts/conf.d/11-lcdfilter-default.conf"
        state: link

    - name: Enable freetype2
      ansible.builtin.lineinfile:
        path: /etc/profile.d/freetype2.sh
        regexp: "^export FREETYPE_PROPERTIES="
        line: export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
    - name: Clear font cache
      command: fc-cache -fv
