---
- name: Load packages variables
  tags: [packages, media, multimedia, audio]
  ansible.builtin.include_vars:
    file: "{{ ansible_facts['distribution'] }}.yml"
    name: distro_packages

- name: Install multimedia packages
  tags: [packages, media, multimedia]
  block:
    - name: Install media packages
      when: ansible_facts['distribution'] == "Archlinux"
      community.general.pacman:
        name: "{{ distro_packages.multimedia_pkgs_media }}"

    - name: Install media packages (aur)
      when: ansible_facts['distribution'] == "Archlinux"
      kewlfft.aur.aur:
        use: paru
        name: "{{ distro_packages.multimedia_pkgs_media_aur }}"
      become: yes
      become_user: aur_builder

    - name: Install audio plugins
      when: ansible_facts['distribution'] == "Archlinux"
      tags: [audio]
      community.general.pacman:
        name: "{{ distro_packages.multimedia_pkgs_audio_plugins }}"
