---
- name: Install utils zsh customizations
  tags: [zsh-customization, zsh-customization-utils]
  vars:
    include_string: '[[ ! -f "{{ system.home }}/.zshrc.d/spark-utils.zsh" ]] || source "{{ system.home }}/.zshrc.d/spark-utils.zsh"'
  block:
    - name: Copy the customization scripts
      ansible.builtin.copy:
        src: "files/spark-utils.zsh"
        dest: "{{ system.home }}/.zshrc.d/spark-utils.zsh"
        owner: "{{ system.username }}"
        group: "{{ system.username }}"
        mode: "0755"

    - name: Check if .zshrc exists
      ansible.builtin.stat:
        path: "{{ system.home }}/.zshrc"
      register: zshrc_stat

    - name: Ensure spark-utils is included in the zshrc file
      ansible.builtin.lineinfile:
        path: "{{ system.home }}/.zshrc"
        regexp: 'spark-utils\.zsh'
        line: "{{ include_string }}"
      when: zshrc_stat.stat.exists
