#!/bin/bash
DNSDOCK_VERSION=${1:-aacebedo\/dnsdock:v1.16.4-amd64}
if docker ps -a | grep 'dnsdock' > /dev/null; then
    echo -n "Found a dnsdock container, removing it..."
    docker rm -vf dnsdock 1> /dev/null
    echo -n "DONE"
    echo ""
fi
if docker ps -a | grep 'dinghy-http-proxy' > /dev/null; then
    echo "Found a dnsdock container, removing it..."
    docker rm -vf dinghy-http-proxy 1> /dev/null
fi

echo "Now starting a new dnsdocker container..."
docker run --restart=always -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock -p 172.17.0.1:53:53/udp "${DNSDOCK_VERSION}"