---
- name: Install logitech packages
  import_tasks: install_packages.yml

- name: Configure logitech
  tags: [logitech]
  block:
  - name: Configure logiops (for MX Master 2S and MX Master 3)
    ansible.builtin.copy:
      src: logitech/logid-mx-master.cfg
      dest: /etc/logid.cfg
    when: is_logitech_unifying.stdout != ""
