---
- name: Install logitech stuff
  tags: [logitech]
  block:
    - name: "Detect Logitech Unifying stuff"
      shell: "lsusb | grep -i logitech | grep Unifying"
      ignore_errors: yes
      register: is_logitech_unifying

    - name: Install logitech packages
      community.general.pacman:
        name:
          - solaar

    - name: Install logitech packages from aur
      kewlfft.aur.aur:
        use: paru
        name:
          - logiops
      become: yes
      become_user: aur_builder

    - name: Configure logiops (for MX Master 2S and MX Master 3S)
      ansible.builtin.copy:
        src: logitech/logid-mx-master.cfg
        dest: /etc/logid.cfg
