- hosts: all
  vars:
    sparkdock_default_path: "{{ current_home }}/.local/spark/sparkdock"

  pre_tasks:
    - name: Auto-detect current user (like sparkdock uses ansible_facts['user_id'])
      tags: [always]
      ansible.builtin.set_fact:
        current_user: "{{ ansible_facts['env']['SUDO_USER'] | default(ansible_facts['user_id']) }}"
        current_home: "/home/{{ ansible_facts['env']['SUDO_USER'] | default(ansible_facts['user_id']) }}"

  roles:
    - role: system
    - role: sparkdock
    - role: sf-toolbox
    - role: packages
    - role: docker
    - role: nvidia
    - role: amd
    - role: gnome
    - role: logitech
    - role: sparkfabrik
    - role: sway
    - role: i3
