---
- name: Install `ajust` packages via Homebrew
  become: yes
  become_user: "{{ system.username | default(current_user) }}"
  community.general.homebrew:
    name:
      - just
      - gum
    state: present
    path: /home/linuxbrew/.linuxbrew/bin
