---
- name: Configure kernel
  tags: [system, kernel]
  block:
    - name: "Check if grub is installed"
      block:
        - stat: path=/boot/grub
          register: grubcfg

    - name: Copy provided mkinitcpio.conf
      tags: [system, mkinitcpio]
      vars:
        enable_encrypt: "{{ (encryption == true) | ternary('encrypt', '') }}"
      ansible.builtin.copy:
        src: files/mkinitcpio.conf
        dest: /etc/mkinitcpio.conf

    - name: Regenerate mkinitcpio.conf
      tags: [system, mkinitcpio]
      shell: mkinitcpio -P

    - name: Regenerate grub config
      tags: [system, mkinitcpio]
      shell: grub-mkconfig -o /boot/grub/grub.cfg
      when: grubcfg.stat.isdir is defined and grubcfg.stat.isdir
